/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 15 00:28:26 GMT 2022
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Foo;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Foo_ESTest extends Foo_ESTest_scaffolding {
    
    @Test(timeout = 4000)
    public void test0()  throws Throwable  {
	Foo foo = new Foo();
	assertTrue(foo.id1 == 0);
	assertTrue(foo.id2 == 10);
       	assertTrue(foo.id3 == 0);
       	assertTrue(foo.id4 == 10);
    }
    
    @Test(timeout = 4000)
    public void test1()  throws Throwable  {
	Foo foo = new Foo();
	assertTrue(foo.id1 == 0);
	assertTrue(foo.id2 == 10);
       	assertTrue(foo.id3 == 0);
       	assertTrue(foo.id4 == 10);
    }
}
