name: staticStatePollution_EVOSUITE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Build Install and Test with Maven
        run: |
          cd evosuite-libs
          export EVOSUITE="$(pwd)/evosuite-master-1.2.0.jar"
          export EVOSUITE_RUNTIME="$(pwd)/evosuite-standalone-runtime-1.2.0.jar"
          cd ..
          cd staticStatePollutionExampl
          mvn clean -DskipTests install
          mvn dependency:copy-dependencies
          cd evosuite-tests
          export CLASSPATH="../target/dependency/hamcrest-core-1.3.jar:../target/dependency/junit-4.11.jar:../target/classes:$EVOSUITE_RUNTIME:."
          javac tutorial/*.java
          java org.junit.runner.JUnitCore tutorial.Foo_ESTest
