name: staticStatePollution

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Build Install and Test with Maven
        run: |
          cd staticStatePollutionExample
          mvn clean install
